objective:
  - SLOPE[fit_intercept=False,q=0.2,reg=0.1]

dataset:
    - Simulated[X_density=1.0,n_features=200,n_samples=500,standardize=True]

solver:
  - PGD
  - PGD_safe_screening[accelerated=True]

# note: use more repetitions to have quantiles on the plot
n-repetitions: 1
