objective:
  - SLOPE[fit_intercept=True,q=0.2,reg=0.1]

dataset:
  - Simulated[X_density=1.0,n_features=200,n_samples=500]

solver:
  - PGD[prox=prox_isotonic]
  - rSLOPE
  - skglm

# note: use more repetitions to have quantiles on the plot
n-repetitions: 1
