name: Tests

on:
  push:
    branches:
      - main
  create:
    tags:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    # Run every Monday at 7:42am UTC.
    - cron: "42 7 * * 1"

jobs:
  test-benchmark:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: jolars/setup-benchopt@main
        with:
          version: git
          branch: benchopt@main
      - run: benchopt test . --env-name bench_test_env -vl

  lint:
    uses: benchopt/template_benchmark/.github/workflows/lint_benchmarks.yml@main
